### ISSUE TITLE
Not failing to compile when I switch two tiny types around

### ISSUE THREAD

**Issue by jamesottaway** [jan-molak/tiny-types#177]
I'm trying to model start/end dates so I can write a function to validate that an event ends after it starts, but the following code compiles where I would have expected the `whoops` function to fail due to the arguments being in the wrong order.

```typescript
import { TinyTypeOf } from 'tiny-types';

class Start extends TinyTypeOf<Date>() { }
class End extends TinyTypeOf<Date>() { }

type Event = {
    start: Start,
    end: End
}

const isValid: (event: Event) => boolean = (event) => endsAfterStarting(event.start, event.end)
const whoops: (event: Event) => boolean = (event) => endsAfterStarting(event.end, event.start)

const endsAfterStarting: (start: Start, end: End) => boolean = (start, end) => end > start;
```

Any ideas?

**Comment by jan-molak** [comment]
Hey @jamesottaway! The challenge with TypeScript is that it's based on [structural subtyping](https://www.typescriptlang.org/docs/handbook/type-compatibility.html). 

Consider [this simple example](https://www.typescriptlang.org/play?ts=4.1.2#code/MYewdgzgLgBGIHcYF44FMkBECGU0AoBKAKGOABtsIIYBlKbAJ1gG9iYOZRIpGBXYFBCN8ABz4AjcgEtgMRmmwATcOQCeMAG7ZyfNAC4YOPCjiJCMFgF9iNspWowAomCWX2nbtH6DhYyTJyCsqqGtq6Bka4aKbwCBbWtqQAZnxggtLgMGgAjnw6+NBMUIb0xQA02a6GLkoJHhwKUHyMYDBFzAB04XqdAOZoUAAq0gC2BBbIU1VK3Tq9A8NjEwDcSWTgECDkaJ3kIH34ufnk+GAYdAzMRJXnSLVEhIRrG5Dbu-uHxwV3zq436CQZWuT2exCAA):

```typescript
const now = new Date()

class Start {
    constructor(public readonly value: Date = now) {}
}

class End {
    constructor(public readonly value: Date = now) {}
}

function equal(start: Start, end: End) {
    return start.value.getTime() === end.value.getTime();
}

console.log(equal(new Start(), new End()));
console.log(equal(new End(), new Start()));
```

Because both `Start` and `End` have the same fields and of the same type, TypeScript considers them to be compatible...

While I'd _love_ for TypeScript to preserve interface information at runtime (see [type erasure](https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-type-erasure)) what I did to get around that limitation in [Serenity/JS](https://github.com/serenity-js/serenity-js) (one of my other projects) was to introduce a custom [`Timestamp`](https://github.com/serenity-js/serenity-js/blob/master/packages/core/src/model/Timestamp.ts) type and use that with my framework's domain events.

This way I had a place to add any comparators and timestamp-specific methods like the ones to calculate duration between two timestamps, etc.

Hope this helps!
Jan
